FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./

RUN npm install

COPY --chown=node:node ./ ./

CMD [ "npm","run","start" ]


# docker run -it -p 4000:3000 -v /home/node/app/node_modules -v ~/frontend:/home/node/app shahan/frontendweb